rem 
rem create user wc identified by wc default tablespace users temporary tablespace temp;
rem alter user wc quota unlimited on users;
rem grant connect, create table , create type, create sequence, create view ,create procedure , create session to wc;

--------------------------------------------------------
--  File created - Saturday-August-16-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type STRING_TABLE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "STRING_TABLE" as table of varchar2(500);

/
--------------------------------------------------------
--  DDL for Sequence PS_TXN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PS_TXN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 2251 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table WC_FOOTBALL_REGIONS
--------------------------------------------------------

  CREATE TABLE "WC_FOOTBALL_REGIONS" 
   (	"ID" NUMBER(2,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"CONTINENT" VARCHAR2(2 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table WC_MATCH_RESULTS
--------------------------------------------------------

  CREATE TABLE "WC_MATCH_RESULTS" 
   (	"GROUP1" VARCHAR2(1 BYTE), 
	"HOME_TEAM_ID" NUMBER(2,0), 
	"AWAY_TEAM_ID" NUMBER(2,0), 
	"HOME_GOALS" NUMBER(2,0), 
	"AWAY_GOALS" NUMBER(2,0), 
	"SDM_ID" NUMBER(2,0), 
	"LOCAL_START_TIME" DATE, 
	"SCORING_PROCESS" VARCHAR2(20 BYTE), 
	"ID" NUMBER(2,0), 
	"RATING" NUMBER(3,2)
   ) ;
--------------------------------------------------------
--  DDL for Table WC_MATCH_TAGS
--------------------------------------------------------

  CREATE TABLE "WC_MATCH_TAGS" 
   (	"TAG_ID" NUMBER(4,0), 
	"MATCH_ID" NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Table WC_STADIUMS
--------------------------------------------------------

  CREATE TABLE "WC_STADIUMS" 
   (	"ID" NUMBER(2,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"LATTITUDE" NUMBER(5,2), 
	"LONGITUDE" NUMBER(5,2)
   ) ;
--------------------------------------------------------
--  DDL for Table WC_TAGS
--------------------------------------------------------

  CREATE TABLE "WC_TAGS" 
   (	"ID" NUMBER(4,0), 
	"TAG" VARCHAR2(200 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table WC_TEAMS
--------------------------------------------------------

  CREATE TABLE "WC_TEAMS" 
   (	"ID" NUMBER(2,0), 
	"COUNTRY" VARCHAR2(3 BYTE), 
	"GROUP1" VARCHAR2(1 BYTE), 
	"SEQ_IN_GROUP" NUMBER(1,0), 
	"FIFA_RANK" NUMBER(3,0), 
	"RGN_ID" NUMBER(2,0)
   ) ;
--------------------------------------------------------
--  DDL for View RUNNING_SCORE_STATS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RUNNING_SCORE_STATS" ("MATCH_DATE", "SHORT_AVG", "TOTAL_AVG", "GOALS_SCORED_ON_DAY") AS 
  with matches as 
( select m.id
,      m.LOCAL_START_TIME match_date
,      m.HOME_GOALS+m.AWAY_GOALS goals_count
from   wc_match_results m
)
, running_stats as 
(select trunc(match_date) match_date
,      avg(goals_count) over (order by match_date rows 4 preceding) running_avg_short
,      avg(goals_count) over (order by match_date ) running_avg_all
,      sum(goals_count) over (partition by match_date) goals_scored
from   matches
)
select match_date
,      avg(running_avg_short) short_avg
,      avg(running_avg_all) total_avg
,      sum(goals_scored) goals_scored_on_day
from   running_stats
group by match_date
order
by  1;
REM INSERTING into WC_FOOTBALL_REGIONS
SET DEFINE OFF;
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (1,'Middle East','AS');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (2,'Africa','AF');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (3,'Far East','AS');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (4,'South America','AM');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (5,'North America','AM');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (6,'Central America','AM');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (7,'North Western Europe','EU');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (8,'Eastern Europe','EU');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (9,'Southern Europe','EU');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (10,'Pacific','PC');
REM INSERTING into WC_MATCH_RESULTS
SET DEFINE OFF;
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,1,7,1,1,8,to_timestamp('28-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'01-;|h',49,2.5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,9,13,2,0,1,to_timestamp('28-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'1-1;',50,2.5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,6,3,2,1,6,to_timestamp('29-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-100;',51,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,14,10,1,1,11,to_timestamp('29-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-01;1100|h',52,2.5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,21,17,1,0,5,to_timestamp('01-JUL-14','DD-MON-RR HH.MI.SSXFF AM'),'-0;',55,5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,29,28,2,1,12,to_timestamp('01-JUL-14','DD-MON-RR HH.MI.SSXFF AM'),'-;001|',56,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('C',9,10,3,0,8,to_timestamp('14-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'000',5,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('A',4,1,1,4,4,to_timestamp('23-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'101-11;',33,1);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('A',2,3,1,3,11,to_timestamp('23-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-1110;',34,1.25);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('B',6,7,2,0,5,to_timestamp('23-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'00',36,2.5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('B',8,5,0,3,9,to_timestamp('23-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'111',35,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('C',11,12,2,1,11,to_timestamp('14-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'100',6,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('C',9,11,2,1,4,to_timestamp('19-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'001',21,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('C',12,10,0,0,3,to_timestamp('19-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',22,0.2);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('A',1,2,3,1,5,to_timestamp('12-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'10-00;',1,1.25);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('A',3,4,1,0,3,to_timestamp('13-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-0;',2,5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('A',1,3,0,0,6,to_timestamp('17-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',17,0.2);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('A',4,2,0,4,2,to_timestamp('18-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'1-111;',18,1.25);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('B',5,6,1,5,12,to_timestamp('13-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'011111',3,0.83);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('B',7,8,3,1,7,to_timestamp('13-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'0010',4,1.25);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('B',5,7,0,2,1,to_timestamp('18-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'11',19,2.5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('B',8,6,2,3,10,to_timestamp('18-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'10011',20,1);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('H',29,30,2,1,8,to_timestamp('17-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'100',15,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('H',31,32,1,1,7,to_timestamp('17-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'111',16,2.5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('H',29,31,1,0,1,to_timestamp('22-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'111',31,5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('H',32,30,2,4,10,to_timestamp('22-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'111',32,0.83);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('H',32,29,1,0,5,to_timestamp('26-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'111',47,5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('H',30,31,1,1,9,to_timestamp('26-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'111',48,2.5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('D',13,14,1,3,6,to_timestamp('14-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',7,1.25);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('D',15,16,1,2,2,to_timestamp('14-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'101',8,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('D',13,15,2,1,5,to_timestamp('19-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',23,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('D',16,14,0,1,11,to_timestamp('20-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',24,5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('D',16,13,0,1,3,to_timestamp('24-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',39,5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('D',14,15,0,0,8,to_timestamp('24-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',40,0.2);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('E',17,18,2,1,4,to_timestamp('15-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',9,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('E',19,20,3,0,10,to_timestamp('15-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'111',10,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('E',17,19,2,5,12,to_timestamp('20-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'111',25,0.71);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('E',20,18,1,2,9,to_timestamp('20-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',26,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('E',20,17,0,3,2,to_timestamp('25-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'111',41,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('E',18,19,0,0,1,to_timestamp('25-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',42,0.2);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('F',21,22,2,1,1,to_timestamp('15-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'001',11,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('F',23,24,0,0,9,to_timestamp('16-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',12,0.2);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('F',21,23,1,0,8,to_timestamp('21-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'0',27,5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('F',24,22,1,0,7,to_timestamp('21-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'0',28,5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('F',24,21,2,3,10,to_timestamp('25-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'10101',43,1);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('F',22,23,3,1,12,to_timestamp('25-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',44,1.25);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('G',25,26,4,0,12,to_timestamp('16-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'0000',13,1.25);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('G',27,28,1,2,3,to_timestamp('16-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',14,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('G',25,27,2,2,6,to_timestamp('21-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',29,1.25);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('G',28,26,2,2,2,to_timestamp('22-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',30,1.25);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('G',28,25,0,1,11,to_timestamp('26-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',45,5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('G',26,27,2,1,4,to_timestamp('26-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',46,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('C',12,9,1,4,8,to_timestamp('24-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',37,1);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values ('C',10,11,2,1,6,to_timestamp('24-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;',38,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,1,9,2,1,6,to_timestamp('04-JUL-14','DD-MON-RR HH.MI.SSXFF AM'),'0-01;',57,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,19,25,0,1,1,to_timestamp('04-JUL-14','DD-MON-RR HH.MI.SSXFF AM'),'1-;',58,5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,21,29,1,0,4,to_timestamp('05-JUL-14','DD-MON-RR HH.MI.SSXFF AM'),'0-;',60,5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,6,14,0,0,12,to_timestamp('05-JUL-14','DD-MON-RR HH.MI.SSXFF AM'),'-;|h',59,0.2);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,1,25,1,7,8,to_timestamp('08-JUL-14','DD-MON-RR HH.MI.SSXFF AM'),'11111-110;',61,0.63);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,6,21,0,0,5,to_timestamp('09-JUL-14','DD-MON-RR HH.MI.SSXFF AM'),'-;|a',62,0.2);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,19,24,2,0,1,to_timestamp('30-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-00;',53,2.5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,25,30,2,1,1,to_timestamp('30-JUN-14','DD-MON-RR HH.MI.SSXFF AM'),'-;001|',54,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,1,6,0,3,4,to_timestamp('12-JUL-14','DD-MON-RR HH.MI.SSXFF AM'),'11-1;',63,1.67);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID,RATING) values (null,25,21,1,0,1,to_timestamp('13-JUL-14','DD-MON-RR HH.MI.SSXFF AM'),'-;0|',64,5);
REM INSERTING into WC_MATCH_TAGS
SET DEFINE OFF;
Insert into WC_MATCH_TAGS (TAG_ID,MATCH_ID) values (1,1);
Insert into WC_MATCH_TAGS (TAG_ID,MATCH_ID) values (1,3);
Insert into WC_MATCH_TAGS (TAG_ID,MATCH_ID) values (3,3);
Insert into WC_MATCH_TAGS (TAG_ID,MATCH_ID) values (3,20);
REM INSERTING into WC_STADIUMS
SET DEFINE OFF;
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (1,'Est?dio do Maracan?','Rio de Janeiro',23,43);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (4,'Est?dio Nacional Man? Garrincha','Brasilia',15,48);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (5,'Arena de S?o Paulo','Sao Paulo',23,46);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (6,'Est?dio Castel?o','Fortaleza',3,38);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (8,'Est?dio Mineir?o','Belo Horizonte',20,44);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (10,'Est?dio Beira-Rio','Porto Alegre',30,51);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (2,'Arena da Amaz?nia','Manaus',3,60);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (12,'Arena Fonte Nova','Salvador',13,38);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (7,'Arena Pantanal','Cuiaba',15,56);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (3,'Arena das Dunas','Natal',5,35);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (9,'Arena da Baixada','Curitiba',25,49);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (11,'Arena Pernambuco','Recife',8,35);
REM INSERTING into WC_TAGS
SET DEFINE OFF;
Insert into WC_TAGS (ID,TAG) values (1,'referential integrity');
Insert into WC_TAGS (ID,TAG) values (2,'hattrick');
Insert into WC_TAGS (ID,TAG) values (3,'super goal');
Insert into WC_TAGS (ID,TAG) values (4,'extreme heat');
Insert into WC_TAGS (ID,TAG) values (5,'extra time');
Insert into WC_TAGS (ID,TAG) values (6,'penalty shootout');
Insert into WC_TAGS (ID,TAG) values (7,'red card');
Insert into WC_TAGS (ID,TAG) values (8,'injury');
REM INSERTING into WC_TEAMS
SET DEFINE OFF;
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (1,'BRA','A',1,3,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (2,'CRO','A',2,18,8);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (3,'MEX','A',3,20,5);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (4,'CMR','A',4,56,2);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (5,'ESP','B',1,1,9);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (6,'NLD','B',2,15,7);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (7,'CHL','B',3,14,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (8,'AUS','B',4,62,10);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (9,'COL','C',1,8,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (10,'GRC','C',2,12,9);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (11,'CIV','C',3,23,2);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (12,'JPN','C',4,46,3);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (13,'URU','D',1,7,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (14,'CRC','D',2,28,5);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (15,'ENG','D',3,10,7);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (16,'ITA','D',4,9,9);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (17,'SUI','E',1,6,7);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (18,'ECU','E',2,26,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (19,'FRA','E',3,17,7);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (20,'HON','E',4,33,5);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (21,'ARG','F',1,5,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (22,'BIH','F',2,21,8);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (23,'IRI','F',3,43,1);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (24,'NGR','F',4,44,2);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (25,'GER','G',1,2,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (26,'POR','G',2,4,9);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (27,'GHA','G',3,37,2);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (28,'USA','G',4,13,5);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (29,'BEL','H',1,11,7);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (30,'ALG','H',2,22,2);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (31,'RUS','H',3,19,8);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (32,'KOR','H',4,57,3);
SET DEFINE OFF;
